language: php
php:
  - 7.3
sudo: false
services:
  - mysql
before_install:
  - mysql -e 'create database fusio;'
  - mysql -e 'create database fusio_master;'
install:
  - composer install
script:
  - php run_install.php
